name: WalkingWasteland
version: 0.5.1
main: com.SpectralVulpine.walkingwasteland.WalkingWasteland
commands:
  wwl:
    description: Primary Walking Wasteland command, toggles Wasteland mode
    usage: /wwl
    permission: walkingwasteland.commands
    permission-message: You cannot toggle Walking Wasteland with your permission level.
permissions:
  walkingwasteland.commands:
    default: op
  walkingwasteland.immune:
    default: op